# <-- encoding UTF-8 -->
# general plotting tools
# -------------------------------------------
# DOC STRING
# 
# 
# Tianhao Zhao
# Dec 2018
# -------------------------------------------
library(car)  # qqplots

# -------------------------------------------
# function: decorated QQplot for normal distribtion
# NOTE: easy plotting, no title, askes for ylabel; xlabel is "Normal theoretical quantiles"
func_easyQQnorm <- function( vec, ylab = "x", alpha = 0.05 ){
    # input:
    # 1. vec: a numeric/random sample to test if it follows a normal distirbution
    # output:
    # 1. figqq: a list generated by car::qqnorm(), can be input into plot(figqq)
    # dependency:
    # 1. car: std lib
    # -----------
    figqq <- car::qqPlot( vec, main = "", xlab = paste(sep="","Normal theoretical quantiles (alpha = ",alpha,")"), 
                        ylab = paste(sep="","Data quantiles: ",ylab),
                        id = FALSE, lwd = 1, envelope = 1 - alpha
                        )
    return(NULL)
}





# -------------------------------------------













